name: movie_info_provider
description: A starting point for Dart libraries or applications.
version: 1.0.1
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  domain:
    git: https://github.com/minia68/mv-tr__domain.git
  dio: ^5.6.0
  enough_convert: ^1.6.0
  retrofit: ^4.2.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  html: ^0.15.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mocktail: ^1.0.4
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

